version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-d
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    networks:
      - backend

  web:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - cassandra
    networks:
      - backend

networks:
  backend:
    driver: bridge